" use visual bell instead of audio cue
set visualbell

" define plugins
call plug#begin('C:\Programs\Vim\vimfiles\plugins')
  Plug 'elixir-lang/vim-elixir'
  Plug 'slashmili/alchemist.vim'
call plug#end()
